package consts

const (
	ENV_AUTHING_CLIENT_ID     = "AUTHING_CLIENT_ID"
	ENV_AUTHING_CLIENT_SECRET = "AUTHING_CLIENT_SECRET"
	ENV_AUTHING_APP_HOST      = "AUTHING_APP_HOST"
	ENV_AUTHING_REDIRECT_URI  = "AUTHING_REDIRECT_URI"
	ENV_AUTHING_USER_POOL_ID  = "AUTHING_USER_POOL_ID"
)
